### ISSUE TITLE
River biome looks odd

### ISSUE THREAD

**Issue by noopynolife** [Lykrast/Voyage#1]
It is a very minor thing, but I just came across this in my world. It looks pretty cool but I highly doubt this was intentional.

![image](https://user-images.githubusercontent.com/36017265/62327943-191cb180-b4b2-11e9-8778-3f61dbb5c374.png)

**Comment by Lykrast** [comment]
I see the issue but sadly Forge's biome API does not allow changing how rivers work (it's hardcoded in vanilla) without coremods. So well technically that's intentional since I can only add "continental" biomes, so that's not getting fixed.
