### ISSUE TITLE
mis labeled biomes

### ISSUE THREAD

**Issue by Burgerguys** [Lykrast/Voyage#10]
going through my world I am finding that voyage related desert biomes are being mis labelled as lagoon variations, and also one of my friends found a vanilla minecraft ship appear in the desert as well

**Comment by Lykrast** [comment]
Lukewarm and warm lagoons have sand as ground and vanilla ships. While they should have plenty of water, sometimes the generation is unlucky and you just get a flat area of sand. Could you show picture of those "deserts" then?

**Comment by fiddleplum** [comment]
Firstly, you've got a great mod :) I like how it just adds the new biomes and nothing else, keeping things clean and simple, while generating some nice variety in the world.

I'm having this trouble too, where on the first generation of the world the biomes are correct, but then on loads of the server the biome names are wrong and the fog, coldness, etc seem to be wrong as well. They seem to change on every server run. I have Biomes O' Plenty, Traverse Reforged, and Voyage on my server, and it seems like it's only the voyage biomes.

I took a look at the code and see any source of randomness or arbitrariness relating to biome registration, and the only thing I see is this line:

https://github.com/Lykrast/Voyage/blob/0c28217ee4bd5f1baab9630a6502799ef6c5ed1d/src/main/java/lykrast/voyage/init/VoyageBiomes.java#L17

and then later this line:

https://github.com/Lykrast/Voyage/blob/0c28217ee4bd5f1baab9630a6502799ef6c5ed1d/src/main/java/lykrast/voyage/init/VoyageBiomes.java#L44

The HashMap toArray() generates an arbitrary order of the biomes, and perhaps that's changing something about the biomes on every load of the mod. I don't know all the details and don't know forge modding, but it might be something.

**Comment by Lykrast** [comment]
Ooh thanks for the find, I was not aware of this part.

I didn't have any time lately to work on my mods, but I could probably find time to make a small fix like that. No guarantee on the date or if that would actually fix anything tho, but it's worth a try.

**Comment by fiddleplum** [comment]
Okay thanks I really appreciate this :) No worries about the date, and yeah it might not even fix the issue. Fortunately the bug isn't game breaking, just a bit odd when my flower fields biome starts icing over occasionally or the horizon has a greenish color. :P

**Comment by Lykrast** [comment]
Update 1.0.4 with that potential fix should be out soon. Once it's out, please say if the issue seems fixed or not.

**Comment by fiddleplum** [comment]
Hi Lykrast, I was able play for a week, going to new areas that hadn't yet generated and then revisiting them on later restarts of he server, and it seems to be fixed, as the biome names stay the same. However the already existing biomes that were generated with the 1.0.3 version of the mod still show the wrong biome, but I'm guessing that they are actually now showing the correct biome and were just showing the wrong biome when they were first created. I don't know about @Burgerguys, but I'd be good closing this one if you're good with it.

I had also additionally tried creating a new world on a separate server using the older 1.0.3, and couldn't replicate this bug, so I don't know for sure if it's fixed. I think it's one of those tough bugs that doesn't happen every time.

**Comment by Burgerguys** [comment]
I am happy to close the issue as it sounds as the problem is fixed.
