### ISSUE TITLE
Voyage Biomes change on Minecraft restart.

### ISSUE THREAD

**Issue by The-Arcanian** [Lykrast/Voyage#12]
My Voyage Biomes are changing every time I restart Minecraft.
<details>
  <summary>Screenshots</summary>
  
  ![2021-01-27_11 34 36](https://user-images.githubusercontent.com/7005184/106023499-d92d8f00-6094-11eb-8ef7-bdd0c7e6829d.png)
  ![2021-01-27_11 40 31](https://user-images.githubusercontent.com/7005184/106023500-d9c62580-6094-11eb-99c5-e78308b451ed.png)
  ![2021-01-27_11 24 06](https://user-images.githubusercontent.com/7005184/106023501-d9c62580-6094-11eb-9fbf-391d63abe445.png)
  ![2021-01-27_11 26 42](https://user-images.githubusercontent.com/7005184/106023502-da5ebc00-6094-11eb-8ae5-01e2462b913c.png)
  ![2021-01-27_11 29 23](https://user-images.githubusercontent.com/7005184/106023506-da5ebc00-6094-11eb-9228-d67e1bacc722.png)
</details>
<details>
  <summary>Setup</summary>
  
  ```
  Minecraft 1.16.5
  Forge 36.0.1
  AkashicTome-1.4-14
  AppleSkin-mc1.16.2-forge-1.0.14
  astralsorcery-1.16.4-1.13.9
  AutoRegLib-1.6-47
  BetterAdvancements-1.16.3-0.1.0.102
  Botania-1.16.4-410
  bwncr-1.16.4-3.9.16
  ClientTweaks_1.16.3-5.2.0
  cloth-config-forge-4.1.3
  Clumps-6.0.0.13
  Corail-Recycler-NE-1.16.4-360
  CraftingTweaks_1.16.3-12.2.0
  create-mc1.16.3_v0.3e
  curios-forge-1.16.4-4.0.3.3
  DynamicSurroundings-1.16.4-4.0.3.5
  FarmersDelight-1.16.3-0.3.0
  FastFurnace-1.16.3-4.3.0
  FastLeafDecay-v25
  FastWorkbench-1.16.3-4.4.1
  flatbedrock-1.16.4-1.1.6
  ftb-gui-library-1604.1.1.26
  HarderBranchMining-1.16.2-2.61.0.12
  Hwyla-forge-1.10.11-B78_1.16.2
  InventoryEssentials_1.16.3-2.2.0
  InventoryHud_1.16.x.forge-3.1.4
  inventorysorter-1.16.1-18.1.0
  jei-1.16.4-7.6.1.65
  jeiintegration_1.16.4-6.1.1.11
  JustEnoughResources-1.16.3-0.12.0.100
  mgui-1.16.4-3.1.3
  minecolonies-0.13.581-ALPHA-universal
  moreoverlays-1.18.11-mc1.16.4
  morered-1.16.4-2.0.1.2
  observerlib-1.16.4-1.5.1
  Patchouli-1.16.4-48
  Placebo-1.16.3-4.3.3
  QuarkOddities-1.16.3
  Quark-r2.4-297
  SereneSeasons-1.16.4-4.0.0.86-universal
  StorageDrawers-1.16.3-8.2.1
  structurize-0.13.113-ALPHA-universal
  Survive-1.16.5-3.1.2
  swingthroughgrass-1.16.4-1.5.3
  tellme-forge-1.16.4-0.9.1
  tetra-1.16.4-3.5.3
  tombstone-1.16-6.2.3
  totaldarkness-1.2-1.16.3
  UnionLib-1.16.5-3.2.3
  voyage-1.16.4-1.0.3
  WailaHarvestability-mc1.16.2-forge-1.1.13
  ```
  </details>

**Comment by Lykrast** [comment]
I don't have time to look into this but I've been told it's a forge issue, so check in a few forge updates. Might look into it later if I get some time.

**Comment by Landstryder** [comment]
same issue

**Comment by DMSledge** [comment]
Is there a workaround to restore biomes?

**Comment by The-Arcanian** [comment]
@DMSledge It seems fixed for me since it was fixed in Forge. I have moved to a new world but if I recall the biomes went back to what they should be.

**Comment by Lykrast** [comment]
Very good to know.

**Comment by DMSledge** [comment]
FYI I did update forge and the biomes did change, but not to what they were when I first found them. I'm guessing that the biome may have reverted to what it was supposed to be.

**Comment by Swedz** [comment]
This seems to still be an issue for me. Updating to latest forge solved the problem when the world is on single player, but when the same world is on multiplayer the problem persists. Running version `1.16.5 - 36.1.32`.

**Comment by Swedz** [comment]
This is still an issue on latest forge when on a server. Running version `1.16.5 - 36.1.62` now.

**Comment by Lykrast** [comment]
See https://github.com/Lykrast/Voyage/issues/10#issuecomment-886676585. Might be able to test a potential fix, no guarantee if it'll work or when it'll happen as I don't have much time to maintain my mods recently. But at least it's worth a shot if I can.

**Comment by Swedz** [comment]
That may be the case as Sets do not retain insertion order. Though it is strange that I only have this problem on multiplayer, not sure what could be causing that as I'm unfamiliar with how biomes work with Forge.

**Comment by Lykrast** [comment]
Update 1.0.4 with that potential fix should be out soon. Once it's out, please say if the issue seems fixed or not.

**Comment by Lykrast** [comment]
#10 seems to indicate this has been fixed.
