### ISSUE TITLE
Desert Mountains broken terrain

### ISSUE THREAD

**Issue by SissyTrashQueen** [Lykrast/Voyage#2]
![2019-10-19_18 50 13](https://user-images.githubusercontent.com/55768134/67153939-153a4780-f2c9-11e9-898a-fec8f59cc7d5.png)
![2019-10-19_18 51 14](https://user-images.githubusercontent.com/55768134/67153930-defcc800-f2c8-11e9-9894-2a2e9ca14d8b.png)
![2019-10-19_18 51 35](https://user-images.githubusercontent.com/55768134/67153931-df955e80-f2c8-11e9-898d-3aa30b649bc3.png)
![2019-10-19_19 11 04](https://user-images.githubusercontent.com/55768134/67153932-df955e80-f2c8-11e9-885f-b411051abf19.png)

So I've installed Voyage since I started the world and yet I still have broken terrain when the Desert Mountain biome connects with a vanilla one.
EDIT: When I started the world I also had the Bunch of Biomes! mod but didn't notice anything as broken as this with Voyage's biomes and the ones of that mod

**Comment by Lykrast** [comment]
Did you update and/or change any other biome mod after the world was started?

This is a weird issue.

**Comment by SissyTrashQueen** [comment]
I actually did install the mod "Traverse Legacy Continued" after I created this world, but haven't seen any biomes from that mod yet. Could that be the problem?

I'm pretty sure the broken terrain generated before I installed that mod, but I can't recall correctly

**Comment by Lykrast** [comment]
In this case this is the issue. Changing the biomes in an existing world can do those borders.
