### ISSUE TITLE
[suggestion]Config options

### ISSUE THREAD

**Issue by Halfdeaf** [Lykrast/Voyage#5]
It would be awesome if there was a config to tweak the frequency of biomes and to have the option to turn some of them off

**Comment by Lykrast** [comment]
Due to the Forge config changes in 1.14 there's no easy and elegant way of configuring the biome spawn rates at the appropriate time. While I still want to do it it's not an easy fix.

**Comment by Halfdeaf** [comment]
Just a heads up. I've been in contact with Nooby about Traverse and he's found a way to add a config to tweak biome weight. I don't know if Voyage works the same way but I thought I d let you know

**Comment by Lykrast** [comment]
Traverse got an updated which added this option, so I'm reminding me to look into it.
https://github.com/MysticMods/Traverse
