### ISSUE TITLE
Add the Overworld tag to each biome

### ISSUE THREAD

**Issue by Azure3141** [Lykrast/Voyage#7]
Some mods, specifically Terraforged, decide which biomes to include in their custom worldgen model by looking for biomes with the Overworld tag. This is how it achieves compatibility with mods that add biomes. 

The biomes added by Voyage don't have this tag yet, likely because it's a new feature, so it would be greatly appreciated if you could add it to them for compatibility with Terraforged.

**Comment by Lykrast** [comment]
Just to know, is this for 1.14 or 1.15?
